### ISSUE TITLE
Получение количества записей из БД

### ISSUE THREAD

**Issue by chepkasovartem** [egal/egal-framework-php-package#100]
### Ваше предложение связано с проблемой?

Необходимо возвращать количество записей БД.

### Опишите желаемое решение

Существует стандартный action который работает так же как actionGetItems но возвращает только количество записей

### Опишите альтернативы, которые вы рассмотрели

Получать все записи и осуществлять подсчет на стороне клиента.
Добавление кастомного action

**Comment by chepkasovartem** [comment]
18.08.2021

**Comment by rollsover** [comment]
@l-max, что думаешь насчет `actionGetCount`? Пододет ли оно под концепции?
