### ISSUE TITLE
Фильтр по условию exist

### ISSUE THREAD

**Issue by chepkasovartem** [egal/egal-framework-php-package#101]
### Ваше предложение связано с проблемой?

Часто необходимо вернуть записи из таблицы у которых существует хоть одна связанная по определенному relation запись. 

### Опишите желаемое решение

Добавить стандартный в фреймворк фильтр exist реализующий laravel фильтр whereExist.

### Опишите альтернативы, которые вы рассмотрели

1. Добавление в основную сущность поле подсчитывающие количество записей в связанной сущность (слишком перегружено для сущности с множеством relation)
2. Возвращать записи по relation, проверять существование на фронте (медленно)

**Comment by chepkasovartem** [comment]
16.08.2021

**Comment by rollsover** [comment]
duplicate #104
