### ISSUE TITLE
Сортировка по связанным сущностям

### ISSUE THREAD

**Issue by chepkasovartem** [egal/egal-framework-php-package#102]
### Ваше предложение связано с проблемой?

Необходимо добавить сортировку по связанным сущностям модели

### Опишите желаемое решение

Реализовать схожий с предлагаемым фреймворком функционал фильтров.
Добавить возможность сортировать по связанным сущностям ["relation_name.attribute", "direction"]

### Опишите альтернативы, которые вы рассмотрели

Дублировать в основную сущность поля (перегружено для моделей с множественной полиморфной связью)

**Comment by chepkasovartem** [comment]
16.08.2021

**Comment by rollsover** [comment]
Так как универсально нельзя простроить внятную сортировку по любому отношение - реализация самой сортировки лежит на пользователе. Мы предоставим инструмент простой интеграции такой сортировки.

**Comment by rollsover** [comment]
Невозможно адекватно и универсально реализовать.

Как все же делать? Варинты:
1. Делать join поля по которому нужна сортировка в родительскую сущность и сортировать по нему.
2. Сделать view родительской сущности с полем, по которому уже производить сортировку.
