### ISSUE TITLE
Фильтрация связанных сущностей

### ISSUE THREAD

**Issue by chepkasovartem** [egal/egal-framework-php-package#116]
### Ваше предложение связано с проблемой?

Есть необходимость фильтровать возвращаемые связанные сущности для оптимизации запросов.
Например: table_1 - table_2 связаны как one_to_many, необходимо вернуть связанные с table_1 записи из table_2 удовлетворяющие определенному условию.

### Опишите желаемое решение

Добавить фильтр связанных сущностей во фреймворк.

### Опишите альтернативы, которые вы рассмотрели

Отдавать все данные из зависимой сущности и фильтровать на клиенте (не оптимально по времени)

**Comment by chepkasovartem** [comment]
06.09.2021

**Comment by rollsover** [comment]
https://stackoverflow.com/questions/26138920/filter-a-polymorphic-table
