### ISSUE TITLE
Коды/Названия/Теги/Типы у сообщений ошибок (исключений).

### ISSUE THREAD

**Issue by rollsover** [egal/egal-framework-php-package#143]
Проблема заключается в том, что  HTTP код не информативен для фронтов, и им приходится идентифицировать ошибки по тексту сообщейния.

**Comment by annstgn** [comment]
Нельзя сменить тип кода для Exception, поэтому будет отдельный string атрибут internalCode для тела ответа, а int атрибут code будет задавать HTTP-код ответа
