### ISSUE TITLE
Auth сам себя не может вызвать без прав.

### ISSUE THREAD

**Issue by rollsover** [egal/egal-framework-php-package#154]

**Comment by rollsover** [comment]
Нужно поресерчить как вообще в других сервисах это делается.

По моему мнению нужно обязательно выдавать права на доступ текущему сервису. Почему не то?

**Comment by annstgn** [comment]
Помнишь, ты рассказывал о проблеме с доступами сервисов при межсервисном общении? Вроде того, что если в сервисе А указать, что ендпоинт доступен сервису Б, то при обращении Б к А ещё требуется указание, что ендпоинт доступен и самому сервису А. Я правильно поняла?

Чепкасов Артём 
Да

**Comment by annstgn** [comment]
Мы сможем получить доступ к endpoint неаутентифицированным пользователем?
Сутягина Анна[Egal][Backend]  2 мин назад
надо проверять конечно, но вообще не должны, пока не будет указан доступ пользователю с доступом guest

Чепкасов Артём [FABRIKA] [Backend]  1 мин назад
Вот, если мы пишем так * @action register     {@services-access auth}, то проблем нет
если ставим status access, то нужно указывать оба микросервиса

Сутягина Анна[Egal][Backend]  < 1 мин назад
Очень интересно. Ну я поняла, что вам нужно, буду разбираться

**Comment by rollsover** [comment]
Работает, исправлений не требует. Работает на `^v2.0.0beta49`.
