### ISSUE TITLE
UMRT (User Master Refresh Token) для UMT.

### ISSUE THREAD

**Issue by Fessan** [egal/egal-framework-php-package#39]
Функционал нужен для relogin после протухания UMT, чтобы лишний раз не отправлять пароль в запросе.

При логине должен выдаваться UMT и UMRT.

Должен быть endpoint в auth-service, при обращении к которому с UMRT выдавался новый UMT и UMRT.

Время жизни у UMRT - самое максимальное и оно будет соответствовать, кол-ву времени позволенному пользователю находится с текущей сессии в аккаунте (без please relogin).

**Comment by annstgn** [comment]
https://github.com/egal/egal-auth-service/pull/17

**Comment by annstgn** [comment]
https://github.com/egal/egal-docs/pull/58

**Comment by annstgn** [comment]
Добавлен токен обновления UMT, подробнее о том, как этим пользоваться описано в документации.
Переход на версию сопряжен с изменением формата ответа от запроса login, будьте внимательны.
Обновлены следующие пункты документации:
1) [Авторизация](https://egal.github.io/egal-docs/#/server/autorization)
2) [Пример по шагам. Авторизация](https://egal.github.io/egal-docs/#/getting_started/step_by_step?id=_3-%d0%90%d0%b2%d1%82%d0%be%d1%80%d0%b8%d0%b7%d0%b0%d1%86%d0%b8%d1%8f)

**Comment by rollsover** [comment]
@annstgn 🚩 2
