### ISSUE TITLE
Issue templates.

### ISSUE THREAD

**Issue by rollsover** [egal/egal-framework-php-package#54]

**Comment by rollsover** [comment]
Сделал 2 template. На них можно посмотреть [тут](https://github.com/egal/egal-framework-php-package/issues/new/choose). Редактируются [тут](https://github.com/egal/egal-framework-php-package/tree/main/.github/ISSUE_TEMPLATE).

А также сделал, чтобы все Issues и PM появлялись автоматически в проекте Egal. Редактируются [тут](https://github.com/egal/egal-framework-php-package/blob/main/.github/workflows/assign_to_project.yml).

**Comment by rollsover** [comment]
https://github.com/egal/egal-framework-php-package/commit/c3063348ebbe28ab6fd8e724f530ea7409917afe

**Comment by rollsover** [comment]
@l-max @Fessan pls, review

**Comment by l-max** [comment]
Немного подправил опечатки и обращения в тексте
https://github.com/egal/egal-framework-php-package/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
