### ISSUE TITLE
Ошибка после вызова action из Web Service используя Request.

### ISSUE THREAD

**Issue by rollsover** [egal/egal-framework-php-package#63]
- Egal Version: v2.0.0beta29

### Описание:

Ошибка на стороне библиотеки. Также необходимо поправить в Web Service.

### Действия по воспроизведению:

1. Используя Web Service v2.0.0beta21 попробовать вызвать любой action.
2. Далее в Web Service появится ошбки:

![image_2021-07-02_14-05-56](https://user-images.githubusercontent.com/51847757/124245834-92175e80-db4a-11eb-9843-f86a98691be6.png)

![image_2021-07-02_14-07-25](https://user-images.githubusercontent.com/51847757/124246050-c3902a00-db4a-11eb-815a-91591d412085.png)

**Comment by rollsover** [comment]
Необходимо сделать Review, так как надо было срочно залить для пользователей.

**Comment by rollsover** [comment]
Также [обновил web-service](https://github.com/egal/egal-web-service/releases/tag/v2.0.0beta22)

**Comment by rollsover** [comment]
@l-max pls, review

**Comment by l-max** [comment]
closed
