### ISSUE TITLE
Ошибка при создании записей в другом микросервисе 

### ISSUE THREAD

**Issue by chepkasovartem** [egal/egal-framework-php-package#66]
- Egal Version: fix_service_not_responding, 2.0.0beta31
- PHP Version: 7.4
- Database Driver & Version: egalbox/postgres:2.0.0
- RabbitMQ Version or Docker Image: bitnami/rabbitmq

### Описание:

При запуски seeder, создающий записи в другом микросервисе, возвращается ошибка

![image](https://user-images.githubusercontent.com/87056677/124703947-71218580-df1d-11eb-8aff-eec68b496572.png)

**Comment by l-max** [comment]
Проблема была в том что при отправке запроса в другой микросервис код зацикливался. Нужно было отключить проверку на авторизацию при запросе токенов из сервиса auth.

**Comment by l-max** [comment]
Код на ревью
