### ISSUE TITLE
Валидация моделей на model saving event

### ISSUE THREAD

**Issue by chepkasovartem** [egal/egal-framework-php-package#70]
### Ваше предложение связано с проблемой?

Приоритет event saving выше, чем event creating, валидация моделей происходит раньше, чем отрабатывают кастомные event, нет возможности поставить свои значения в required fields которые не должны приходить с клиента

(Напишите свой ответ здесь.)

### Опишите желаемое решение

Вынести валидацию в отдельный event с приоритетом ниже, чем у пользовательских событий

### Опишите альтернативы, которые вы рассмотрели

Для таких полей отказаться от валидации фреймворка, обрабатывать руками

**Comment by rollsover** [comment]
Еще раз опишу своими словами:
Валидация происходит на event `saving`, но могут разработчики дополнять модель после ивента (на ивенте `created`).
И так получается, что разработчиком все сделано правильно, но валидация не проходит.

Что надо сделать:
Перенести валидацию на более низкий уровень, допустим перед отправкой в БД или что-то типа того

**Comment by rollsover** [comment]
Примерная оценка по времени: 10 часов.

**Comment by rollsover** [comment]
@annstgn 🚩 2
