### ISSUE TITLE
Фильтрация по отношение вызывается ошибка несуществования метода описывающего отношение.

### ISSUE THREAD

**Issue by chepkasovartem** [egal/egal-framework-php-package#72]
- Egal Version: dev-fix_service_not_responding
- PHP Version: 7.4
- Database Driver & Version: Не зависит.
- RabbitMQ Version or Docker Image: Не зависит.

### Описание:

Не фильтруется по отношению. Смотри "Действия по воспроизведению".

А также при фильтрации по несуществующему relation не вызывается ошибка.

### Действия по воспроизведению:

1. Описываем property relation в snake case в Class PHPDoc Block.
2. Описываем relation методом с названием в camel case
3. Получаем ошибку, что не существует метод (название метода соответствует названию отношения в snake case).
    - Ожидалось что он обратится к методу из пункта номер 2.

**Comment by rollsover** [comment]
Не тот PR...

**Comment by chepkasovartem** [comment]
Нужно как можно быстрее 02.08.2021
