### ISSUE TITLE
При истечении срока жизни токена возвращает status code 200  

### ISSUE THREAD

**Issue by chepkasovartem** [egal/egal-framework-php-package#76]
- Egal Version: dev-fix_service_not_responding
- PHP Version: 7.4
- Database Driver & Version: Не зависит.
- RabbitMQ Version or Docker Image: Не зависит.

### Описание:

При истечении жизни jwt токена при попытке получить доступ к endpoint возвращает ошибку с status code 200

1. Получить токен аутентификации
2. Дождаться когда срок действия токена истечет
3. Отправить запрос на endpoint требующий аутентификации

**Comment by rollsover** [comment]
Выяснилось:
* При невозможности расшифровать токен ошибка выпадает раньше, чем отправляется сообщение начала обработки.
* При получении сообщения ответа без сообщения начала обработки либо при получении сообщения ошибки без сообщения начала обработки - в Responce итоговый код ошибки - 200.
