### ISSUE TITLE
Ошибка при указаний не корректных фильтров для запроса getItems.

### ISSUE THREAD

**Issue by l-max** [egal/egal-framework-php-package#92]
- Egal Version: v2.0.0beta36
- PHP Version: 7.4

### Описание:

При запросе getItems с указанием некорректных фильтров возникает ошибка
```
"message": "SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type bigint: \"\" (SQL: select count(*) as aggregate from \"speakers\" where \"id\" = )",
```

### Действия по воспроизведению:

1. сделать запрос на service/Model/getItems с указанием фильтров
```
"filter": [
          [
              "id",
              "eq",
              ""
          ]
        ]
```

либо такими фильрами

```
"filter": [
          [
              "",
              "eq",
              ""
          ]
        ]
```

**Comment by l-max** [comment]
Нужно валидировать поля, и желательно проверить на уязвимости.

**Comment by chepkasovartem** [comment]
18.08.2021
"error_message": "SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type uuid: \" \" (SQL: select count(*) as aggregate from \"table\" where \"id\"  = " " )"
"filter": [
        ["id", "eq", " "]
    ]

**Comment by rollsover** [comment]
Value мы не как не сможем проверять, очень сильно скажется на производительности, так как решение - делать валидаторы на эти все поля. А Если там еще и будут отношения - вообще будет все плохо, так как лазить надо будет по всему проекту.

Если понадобится - переоткрывайте проблему с комментом, что надо валидировать value. И если будем делать - делать надо с возможностью отключения этого.
